// actionTypes.js
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const FETCH_CHATS_SUCCESS = 'FETCH_CHATS_SUCCESS';
export const FETCH_CHATS_FAILURE = 'FETCH_CHATS_FAILURE';
export const SEND_MESSAGE_FAILURE= 'SEND_MESSAGE_FAILURE;'
// actionTypes.js
export const ADD_USER = 'ADD_USER';
export const ADD_USER_FAILURE = 'ADD_USER_FAILURE';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';
