export const CREATE_PERSONAL_CHAT_SUCCESS = "CREATE_PERSONAL_CHAT_SUCCESS";
export const CREATE_PERSONAL_CHAT_FAILURE = "CREATE_PERSONAL_CHAT_FAILURE";
export const GET_PERSONAL_CHATS_SUCCESS = "GET_PERSONAL_CHATS_SUCCESS";
export const GET_PERSONAL_CHATS_FAILURE = "GET_PERSONAL_CHATS_FAILURE";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAILURE = "GET_ALL_USERS_FAILURE";
